import type { Metadata } from "next";
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import { CssBaseline } from "@mui/material";
import { Montserrat } from "next/font/google";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import axios from "axios";
import { FetchHeaderData } from "./utils/FetchHeaderData";
import Header from "./globals/Header";


axios.defaults.baseURL = process.env.NEXT_PUBLIC_API_URL;
axios.defaults.headers.post["Content-Type"] = "application/json";
axios.defaults.headers.put["Content-Type"] = "application/json";
axios.defaults.withCredentials = true;

export const dynamicParams = false

const montSerrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerData = await FetchHeaderData();

  return (
    <html lang="en" className={montSerrat.className}>
      <CssBaseline />
      <body>
        <ThemeProvider theme={theme}>
        {headerData && (
          <Header logo={headerData.logo.url} title={headerData.title}/>
        )}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
